sql: status
tableName: status
primaryKey: uuid
table:
    uuid: CHAR(36)
    writeTime: INT
    health: INT
    fire: INT
    foodLevel: INT
    foodExhaustionLevel: REAL
    foodSaturationLevel : INT
    xpLevel : INT
    xpP: REAL
    playerGameType: INT