sql: status
tableName: advancements
primaryKey: uuid
table:
    uuid: CHAR(36)
    writeTime: INT
    adventure: TEXT
    adventureFinish: INT
    end: TEXT
    endFinish: INT
    husbandry: TEXT
    husbandryFinish: INT
    nether: TEXT
    netherFinish: INT
    recipes: TEXT
    recipesFinish: INT
    story: TEXT
    storyFinish: INT